name: CI

on: [pull_request, push]

jobs:
  push_to_gitlab:

    runs-on: ubuntu-latest
    
    steps:
    - secrets: GITLAB_ACCESS_TOKEN
    - uses: actions/checkout@v1
    - name: Add gitlab remote
      run: git remote add gitlab https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.icp.uni-stuttgart.de/kai/espresso_mirror
    - name: push to PR branch
      if: github.event_name == 'pull_request'
      run: |
        git remote -v
        pr_number=$(jq .pull_request.number ${GITHUB_EVENT_PATH})
        git checkout -b PR-${pr_number}
        git push gitlab
