name: CI

on: [push, pull_request]

jobs:
  push_to_gitlab:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Add gitlab remote
      run: git remote add gitlab https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.icp.uni-stuttgart.de/kai/espresso_mirror.git
    - name: push to remote
      run: git push gitlab test
